### ISSUE TITLE
There is something will deprecate and will not work in the next major version

### ISSUE THREAD

**Issue by rocwong-cn** [zbtang/React-Native-TextInputLayout#1]
Warning:U R manually calling a React .PropTypes validation function for the 'position' prop on 'StyleSheet fullscreen '.

**Comment by zbtang** [comment]
which version of RN do you use?

**Comment by rocwong-cn** [comment]
`"react": "^15.2.1",
"react-native": "0.31.0",`

run at iphone6 simulator

**Comment by rocwong-cn** [comment]
some details that I wrote there:
FYI.[http://bbs.reactnative.cn/topic/2149/分享一个material-design的textinput组件/2](url)

`Warning: You are manually calling a React.PropTypes validation function for the`justifyContent`prop on`ScrollView`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.`

**Comment by zbtang** [comment]
I have tested on '0.31.0' just now ,but got no warning. Do you have other dependences ? Maybe other third-party dependences cause this warning ?

**Comment by rocwong-cn** [comment]
There are all my dependences : 
`"dependencies": {
    "native-base": "^0.5.4",
    "react": "^15.2.1",
    "react-native": "0.31.0",
    "react-native-vector-icons": "^2.0.3",
    "rn-textinputlayout": "^1.0.0"
  }`
And the warning occurred  when I am not import native-base package.

**Comment by zbtang** [comment]
I guess it's `native-base` that cause this warning, but I can't make sure. You can use exclusive method to make sure .
