### ISSUE TITLE
Showing error when used with react-native 0.40

### ISSUE THREAD

**Issue by waqas19921** [zbtang/React-Native-TextInputLayout#5]
![sketch](https://cloud.githubusercontent.com/assets/17469425/22538723/62b821d4-e936-11e6-8674-a763436392eb.png)

**Comment by zbtang** [comment]
hi, which platform are you on? I tried 'V0.40.0' of both platform, but this issue did not repeat.

**Comment by chicojasl** [comment]
Its happening to me too.

I started to see a little bit of the code and I found a bug. 

You are doing a `flatten` on line 73:
```js
this._oriEdtStyle = StyleSheet.flatten([edtChild.props.style])    // Line 73
```
and then in the line 98 tries to get the `fontSize` of it:

```js
let {height, fontSize}= this._oriEdtStyle;        // Line 98
let labelHeight = fontSize + 3;                   // Line 99
```
if my input does not have `fontSize` in the style, the line 99 results a `NaN`.

This makes that the `interpolate` gets the exception in the animation.
```js
let labelTransY = this.state.labelAnimationValue.interpolate({
  inputRange: [0, 1],
  outputRange: [height + labelHeight >> 1, labelHeight - this.props.labelFontSize]
});
```

**Comment by zbtang** [comment]
Thanks, I'll fix it
